# Generated by Django 5.2.7 on 2025-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('popularity', models.FloatField(default=0)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('adult', models.BooleanField(default=False)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('genre_ids', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
